"""extend task model for H-ASAE and add task dependencies

Revision ID: 227da7fa7ba5
Revises: bd63f2365220
Create Date: 2026-04-26 14:00:56.061417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227da7fa7ba5'
down_revision: Union[str, None] = 'bd63f2365220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency')
    )
    op.create_index(op.f('ix_task_dependencies_depends_on_task_id'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_user_id'), 'task_dependencies', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('difficulty_level', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('tasks', sa.Column('energy_required', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('tasks', sa.Column('is_splittable', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('tasks', sa.Column('is_strict_time', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('tasks', sa.Column('earliest_start_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('latest_finish_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('auto_schedule_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('tasks', sa.Column('schedule_flexibility', sa.String(length=20), server_default='flexible', nullable=False))
    op.alter_column('tasks', 'difficulty_level', server_default=None)
    op.alter_column('tasks', 'energy_required', server_default=None)
    op.alter_column('tasks', 'is_splittable', server_default=None)
    op.alter_column('tasks', 'is_strict_time', server_default=None)
    op.alter_column('tasks', 'auto_schedule_enabled', server_default=None)
    op.alter_column('tasks', 'schedule_flexibility', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'schedule_flexibility')
    op.drop_column('tasks', 'auto_schedule_enabled')
    op.drop_column('tasks', 'latest_finish_at')
    op.drop_column('tasks', 'earliest_start_at')
    op.drop_column('tasks', 'is_strict_time')
    op.drop_column('tasks', 'is_splittable')
    op.drop_column('tasks', 'energy_required')
    op.drop_column('tasks', 'difficulty_level')
    op.drop_index(op.f('ix_task_dependencies_user_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
