"""add_auth_provider_fields

Revision ID: 41eee0b895e7
Revises: f03b5b36fca4
Create Date: 2026-04-26 11:45:22.543506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41eee0b895e7'
down_revision: Union[str, None] = 'f03b5b36fca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

auth_provider_enum = sa.Enum('email', 'google', 'apple', name='authprovider')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('auth_provider', auth_provider_enum, server_default='email', nullable=False))
    op.add_column('users', sa.Column('provider_user_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    op.alter_column('users', 'auth_provider', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.execute("UPDATE users SET hashed_password = '' WHERE hashed_password IS NULL")
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'auth_provider')
    auth_provider_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
