"""add daily_schedules and schedule_blocks tables

Revision ID: f03b5b36fca4
Revises: 227da7fa7ba5
Create Date: 2026-04-26 14:06:40.504000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03b5b36fca4'
down_revision: Union[str, None] = '227da7fa7ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('is_overloaded', sa.Boolean(), nullable=False),
    sa.Column('overload_message', sa.Text(), nullable=True),
    sa.Column('total_scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'schedule_date', name='uq_user_schedule_date')
    )
    op.create_index(op.f('ix_daily_schedules_schedule_date'), 'daily_schedules', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_daily_schedules_user_id'), 'daily_schedules', ['user_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['daily_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blocks_schedule_id'), 'schedule_blocks', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_user_id'), 'schedule_blocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_blocks_user_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_schedule_id'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index(op.f('ix_daily_schedules_user_id'), table_name='daily_schedules')
    op.drop_index(op.f('ix_daily_schedules_schedule_date'), table_name='daily_schedules')
    op.drop_table('daily_schedules')
    # ### end Alembic commands ###
